---
- name: Launch Weatherbit instance
  hosts: localhost
  vars_files:
    - ./config/credentials.yaml
    - ./config/api.yaml
  tasks:
    - include_tasks: ./install/install_ansible_requirements_task.yaml
    - include_tasks: ./launch_instance_task.yaml
      vars:
        access_key: "{{aws_access_key}}"
        secret_key: "{{aws_secret_key}}"
        key_path: "{{key}}"
        instance_name: "{{k_instance_name}}"
        group_name: "{{k_group_name}}"
        instance_type: "{{k_instance_type}}"
        image: "{{k_image}}"
        security_group: "{{k_security_group}}"
        region: "{{k_region}}"
        elastic_ip: "{{k_elastic_ip}}"
    - include_tasks: ./add_to_host_task.yaml
      vars:
        key_location: "{{key_path}}"
        ip: "{{k_elastic_ip}}"
        group_name: "{{k_group_name}}"

- name: Set up API
  hosts: "{{k_group_name}}"
  remote_user: ubuntu
  vars_files:
    - ./config/api.yaml
  become: yes
  tasks:
    - include_tasks: ./install/install_universal_task.yaml
    - include_tasks: ./install/install_docker_task.yaml
    - shell: docker pull alexpena9291/cloud_computing:weather_api
    - shell: docker run -d -p 8080:8080 alexpena9291/cloud_computing:weather_api



...