---
- name: Install and Run Kafka
  hosts: localhost
  vars_files:
    - ./config/credentials.yaml
    - ./config/kafka.yaml
  tasks:
    - include_tasks: ./launch_instance_task.yaml
      vars:
        access_key: "{{aws_access_key}}"
        secret_key: "{{aws_secret_key}}"
        key_path: "{{key}}"
        instance_name: "{{k_instance_name}}"
        group_name: "{{k_group_name}}"
        instance_type: "{{k_instance_type}}"
        image: "{{k_image}}"
        security_group: "{{k_security_group}}"
        region: "{{k_region}}"
        elastic_ip: "{{k_elastic_ip}}"


- name: Run
  hosts: all
  remote_user: ubuntu
  vars_files:
    - ./config/credentials.yaml
    - ./config/kafka.yaml
  become: yes
  tasks:
    - include_tasks: ./install/universal.yaml
    - include_tasks: ./install/kafka.yaml
    - include_tasks: ./setup/kafka_server.yml
      vars:
        instance_name: "{{consumer_instance_name}}"
        kafka_ip: "{{k_elastic_ip}}"
        access_key: "{{aws_access_key}}"
        secret_key: "{{aws_secret_key}}"
...
