---
- name: Launch Instance
  hosts: localhost
  vars_files:
    - ./config/credentials.yaml
    - ./config/retriever.yaml
    - ./config/kafka.yaml
    - ./config/api.yaml
    - ./config/k8.yaml
  tasks:
    - include_tasks: ./install/install_ansible_requirements_task.yaml
    - include_tasks: ./cloud/launch_instance_task.yaml
      vars:
        access_key: "{{aws_access_key}}"
        secret_key: "{{aws_secret_key}}"
        key_path: "{{key}}"
        instance_name: "{{lookup('vars', item + '_instance_name')}}"
        group_name: "{{lookup('vars', item + '_group_name')}}"
        instance_type: "{{lookup('vars', item + '_instance_type')}}"
        image: "{{lookup('vars', item + '_image')}}"
        security_group: "{{lookup('vars', item + '_security_group')}}"
        region: "{{lookup('vars', item + '_region')}}"
        elastic_ip: "{{lookup('vars', item + '_elastic_ip')}}"
      loop:
        - r # for retriever
        - k # for kafka
        - a # for api
        - k8 # for kube master
    - include_tasks: ./cloud/add_to_host_task.yaml
      vars:
        key_location: "{{key_path}}"
        ip: "{{lookup('vars', item + '_elastic_ip')}}"
        group_name:
          - "{{lookup('vars', item + '_group_name')}}"
          - k8
      loop:
        - r # for retriever
        - k # for kafka
        - a # for api
        - k8 # for kube master

- name: Configure k8 Nodes
  hosts: k8
  remote_user: ubuntu
  # vars_files:
  #   - ./config/credentials.yaml
  #   - ./config/retriever.yaml
  #   - ./config/kafka.yaml
  #   - ./config/api.yaml
  #   - ./config/k8.yaml
  # become: yes
  tasks:
    - include_tasks: ./install/install_universal_task.yaml
    - include_tasks: ./install/install_docker_task.yaml
    - include_tasks: ./kubernetes/node_task.yaml

- name: Configure k8 nodes
  hosts: "{{k8_group_name}}"
  remote_user: ubuntu
  vars_files:
    - ./config/k8.yaml
    - ./config/kafka.yaml
  become: yes
  tasks:
    - include_tasks: ./kubernetes/master_task.yaml
    - include_tasks: ./docker/containerize_retriever_task.yaml
    # TODO: use bitnami instead of janky image
    - include_tasks: ./install/install_kafka_task.yaml
    - include_tasks: ./setup/kafka_server.yaml
      vars:
        instance_name: "{{k_instance_name}}"
        kafka_ip: "{{k_elastic_ip}}"
    - include_tasks: ./docker/containerize_kafka_task.yaml
    # TODO: completely redo api containerization
    # TODO: get images built and pushed to a registry

- name: Configure k8 minion
  hosts: "{{k8_group_name}}"
  remote_user: ubuntu
  vars_files:
    - ./config/retriever.yaml
    - ./config/kafka.yaml
    - ./config/api.yaml
  become: yes
  tasks:
    - include_tasks: ./kubernetes/minion_task.yaml
...
