---
k_instance_name: geojson_api
k_group_name: api
k_instance_type: t2.medium
k_image: ami-00399ec92321828f5
k_security_group: weatherbit_api_security
k_region: us-east-2
k_elastic_ip: 18.189.79.44
...
