---
aws_access_key: AKIA5XZ22SODWMN26YG3
aws_secret_key: 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
key: cloud_computing_main
weatherbit_key: 0e8aeccfa150491880a30ffb53a3e4ba
key_path: ~/.ssh/cloud_computing_main.pem
...
