- name: Run zookeeper container
  shell: docker run -dtp 2181:2181 --name zoo kafka

- name: Start zookeeper server
  shell: docker exec -d zoo kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties

- name: Start kafka container
  shell: docker run -dtp 9092:9092 --name kaf kafka

- name: Start kafka server
  shell: docker exec -d kaf kafka/bin/kafka-server-start.sh kafka/config/server.properties
