---
- name: "Set Up Database"
  hosts: localhost
  vars_files:
    - ./config/credentials.yaml
    - ./config/database.yaml
  tasks:
    - include_tasks: ./launch_instance_task.yaml
      vars:
        access_key: "{{aws_access_key}}"
        secret_key: "{{aws_secret_key}}"
        key_path: "{{key_path}}"
        instance_name: "{{instance_name}}"
        group_name: "{{db_group_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        security_group: "{{security_group}}"
        region: "{{region}}"
        elastic_ip: "{{elastic_ip}}"

- name: "Load Software onto Baremetal"
  vars_files:
    - ./config/database.yaml
  groups: "{{db_group_name}}"
  become: yes
  tasks:
    - include_tasks: ./install/install_docker_task.yaml
    - include_tasks: ./install/install_influxdb_task.yaml
    - include_tasks: ./run/run_influxdb_task.yaml
...
